spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=docentes_db
spring.datasource.password=docentes123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8081